<?php
tcpdf();
$obj_pdf = new TCPDF('P', PDF_UNIT, "A4", true, 'UTF-8', true);
$obj_pdf->SetCreator("Hendy Andrianto S.Kom (www.facebook.com/opchaky.it)");
$toko = "LEMBAGA PENDIDIKAN KETERAMPILAN";
$hal = "GITA PERTIWI";
$alamat = "PUSAT : JL. KEBON TIWU I NO. 10 TASIKMALAYA";
$tlp = "(0265) 323445 HP. 085295168608";
$cabang = "CABANG : JL. RAYA TIMUR BOROLONG CILAMPUNG HILIR SINGAPARNA"."\n"."HP. 085353292292";
$judul = $alamat . "\n" . "TELP. " . $tlp;
$foto = "profile.jpg";
$obj_pdf->SetTitle($toko);
$obj_pdf->SetDefaultMonospacedFont('helvetica','B','12');
$obj_pdf->SetHeaderData($foto, 30, $toko , $hal . "\n" . $judul . "\n" . $cabang);
$obj_pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', 9));
$obj_pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));
$obj_pdf->SetDefaultMonospacedFont('helvetica');
$obj_pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$obj_pdf->SetFooterMargin(PDF_MARGIN_FOOTER);
$obj_pdf->SetMargins(10, 34, 10);
$obj_pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);
$obj_pdf->SetFont('helvetica', '', 10);
$obj_pdf->setFontSubsetting(FALSE);
$obj_pdf->SetDisplayMode('fullpage', 'SinglePage', 'UseNone');
$obj_pdf->SetFillColor(255, 235, 235);
$obj_pdf->AddPage();
$obj_pdf->SetFont('helvetica', 'B', 9);
$txt = 'LAPORAN HISTORI KEHADIRAN KURSUS';
$obj_pdf->MultiCell(200, 10, $txt, 0, 'C', 0, 1, '', '', true, 0, false, true, 10, 'M');
$obj_pdf->SetFont('helvetica', '', 8);
$ckdata = $this->db->get_where('view_member_kursus',array('kode'=>$kode))->result();
foreach ($ckdata as $key) {
	$tipena = $key->nama_tipe;
}
$txxt = "Tipe Kursus : " . $tipena;
$obj_pdf->SetFont('helvetica', '', 8);
$obj_pdf->MultiCell(100, 10, $txxt, 0, 'L', 0, 1, '', '', true, 0, false, true, 10, 'M');
$obj_pdf->SetFont('helvetica', '', 8);
$obj_pdf->MultiCell(8, 5, 'No.', 1, 'C', 1, 0, '', '', true, 0, false, true, 5, 'M');
$obj_pdf->MultiCell(50, 5, 'Nama Instruktur', 1, 'C', 1, 0, '', '', true, 0, false, true, 5, 'M');
$obj_pdf->MultiCell(25, 5, 'Tanggal', 1, 'C', 1, 0, '', '', true, 0, false, true, 5, 'M');
$obj_pdf->MultiCell(25, 5, 'Jam Mulai', 1, 'C', 1, 0, '', '', true, 0, false, true, 5, 'M');
$obj_pdf->MultiCell(25, 5, 'Jam Selesai', 1, 'C', 1, 0, '', '', true, 0, false, true, 5, 'M');
$obj_pdf->MultiCell(20, 5, 'Menit Kursus', 1, 'C', 1, 0, '', '', true, 0, false, true, 5, 'M');
$obj_pdf->MultiCell(37, 5, 'Fasilitas', 1, 'C', 1, 1, '', '', true, 0, false, true, 5, 'M');
$ckdata = $this->db->query("SELECT tbl_username.nama as nama_instruktur,tbl_mobil.nama as nama_fasilitas,tbl_mulai.tgl_mulai,tbl_mulai.tgl_selesai FROM tbl_mulai INNER JOIN tbl_username ON tbl_mulai.instruktur = tbl_username.id INNER JOIN tbl_mobil ON tbl_mulai.fasilitas = tbl_mobil.id WHERE tbl_mulai.kode_member = '$kode' AND tbl_mulai.status = '0'")->result();
foreach ($ckdata as $row) {
    $x++;
    $nama = $row->nama_instruktur;
    $tgl = date("d-m-Y",strtotime($row->tgl_mulai));
    $waktu_mulai = date("H:i:s",strtotime($row->tgl_mulai));
    $waktu_selesai = date("H:i:s",strtotime($row->tgl_selesai));
    $fasilitas = $row->nama_fasilitas;
    $a = new DateTime($waktu_mulai);
  	$b = new DateTime($waktu_selesai);
  	$jmkerja = $b->diff($a);
  	$jmkerja = $jmkerja->format("%H:%I:%S");
    $obj_pdf->MultiCell(8, 5, $x . ".", 1, 'C', 0, 0, '', '', true, 0, false, true, 5, 'M');
    $obj_pdf->MultiCell(50, 5, $nama, 1, 'L', 0, 0, '', '', true, 0, false, true, 5, 'M');
    $obj_pdf->MultiCell(25, 5, $tgl, 1, 'C', 0, 0, '', '', true, 0, false, true, 5, 'M');
    $obj_pdf->MultiCell(25, 5, $waktu_mulai, 1, 'C', 0, 0, '', '', true, 0, false, true, 5, 'M');
    $obj_pdf->MultiCell(25, 5, $waktu_selesai, 1, 'C', 0, 0, '', '', true, 0, false, true, 5, 'M');
    $obj_pdf->MultiCell(20, 5, $jmkerja, 1, 'C', 0, 0, '', '', true, 0, false, true, 5, 'M');
    $obj_pdf->MultiCell(37, 5, $fasilitas, 1, 'L', 0, 1, '', '', true, 0, false, true, 5, 'M');
}
$obj_pdf->Ln(2);
$obj_pdf->lastPage();
$obj_pdf->writeHTML($content, true, false, true, false, '');
$obj_pdf->Output('Laporan Histori Kehadiran ' . $kode .'.pdf', 'I');
?>